# require the branch name to be master
if: branch = master

language: node_js
node_js:
 — “7”
script:
 — echo “Deploy!!”
install:
 — npm install -g firebase-tools
after_success:
 — firebase deploy — project projectId — token $FIREBASE_TOKEN.