# require the branch name to be master
if: branch = master

language: node_js
node_js:
  - "6"
install:
  - npm install -g firebase-tools
script:
  - echo "Deploy!!"
  - npm install
  - npm run build
after_success:
  - firebase deploy --project women-in-tech-ftw --token $FIREBASE_TOKEN.